### ISSUE TITLE
Breaks with the latest haskell-src-exts

### ISSUE THREAD

**Issue by tebello-thejane** [bosu/hscope#11]
`hscope` does not build with the latest `stackage` nightlies, which use `haskell-src-exts`. Please also see https://github.com/bmillwood/pointfree/pull/13

**Comment by suzumiyasmith** [comment]
The same question happened again now.
with lts-8.22, `haskell-src-exts` has version `1.18.*`

**Comment by bosu** [comment]
Hopefully fixed by https://github.com/bosu/hscope/pull/13.

Thanks,
Boris.
